//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace GuiropaIpad.serviceEMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serviceEMSBinding", Namespace="urn:serviceEMS")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(DadosMedicos))]
    public partial class serviceEMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCadastroMedicoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public serviceEMS() {
            this.Url = global::GuiropaIpad.Properties.Settings.Default.GuiropaIpad_serviceEMS_serviceEMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCadastroMedicoCompletedEventHandler getCadastroMedicoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://200.189.176.212/ems/service/serviceEMS.php/getCadastroMedico", RequestNamespace="serviceEMS", ResponseNamespace="serviceEMS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public InfMedicos getCadastroMedico(string id, string representante) {
            object[] results = this.Invoke("getCadastroMedico", new object[] {
                        id,
                        representante});
            return ((InfMedicos)(results[0]));
        }
        
        /// <remarks/>
        public void getCadastroMedicoAsync(string id, string representante) {
            this.getCadastroMedicoAsync(id, representante, null);
        }
        
        /// <remarks/>
        public void getCadastroMedicoAsync(string id, string representante, object userState) {
            if ((this.getCadastroMedicoOperationCompleted == null)) {
                this.getCadastroMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadastroMedicoOperationCompleted);
            }
            this.InvokeAsync("getCadastroMedico", new object[] {
                        id,
                        representante}, this.getCadastroMedicoOperationCompleted, userState);
        }
        
        private void OngetCadastroMedicoOperationCompleted(object arg) {
            if ((this.getCadastroMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadastroMedicoCompleted(this, new getCadastroMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:serviceEMS")]
    public partial class InfMedicos {
        
        private DadosMedicos[] listaDadosMedField;
        
        /// <remarks/>
        public DadosMedicos[] listaDadosMed {
            get {
                return this.listaDadosMedField;
            }
            set {
                this.listaDadosMedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:serviceEMS")]
    public partial class DadosMedicos {
        
        private int id_medicoField;
        
        private string nome_medicoField;
        
        private string uf_crmField;
        
        private int crmField;
        
        private string espField;
        
        /// <remarks/>
        public int id_medico {
            get {
                return this.id_medicoField;
            }
            set {
                this.id_medicoField = value;
            }
        }
        
        /// <remarks/>
        public string nome_medico {
            get {
                return this.nome_medicoField;
            }
            set {
                this.nome_medicoField = value;
            }
        }
        
        /// <remarks/>
        public string uf_crm {
            get {
                return this.uf_crmField;
            }
            set {
                this.uf_crmField = value;
            }
        }
        
        /// <remarks/>
        public int crm {
            get {
                return this.crmField;
            }
            set {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        public string esp {
            get {
                return this.espField;
            }
            set {
                this.espField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCadastroMedicoCompletedEventHandler(object sender, getCadastroMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadastroMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadastroMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfMedicos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfMedicos)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591